# Generated by Django 3.2.5 on 2021-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookKharido', '0003_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cur',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
