# Generated by Django 3.2.5 on 2021-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookKharido', '0005_auto_20210725_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
