# Generated by Django 3.2.5 on 2021-07-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookKharido', '0006_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
