# Generated by Django 3.2.5 on 2021-07-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookKharido', '0007_remove_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
